import React, { createContext, useContext, useState } from "react";

export interface LanguageInfo {
  code: string;
  name: string;
  nativeName: string;
  region: string;
}

export const INDIAN_LANGUAGES: LanguageInfo[] = [
  { code: "en", name: "English", nativeName: "English", region: "National / Official" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", region: "उत्तर एवं मध्य भारत" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", region: "পশ্চিমবঙ্গ / ত্রিপুরা" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", region: "महाराष्ट्र" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", region: "ఆంధ్రప్రదేశ్ / తెలంగాణ" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", region: "தமிழ்நாடு" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", region: "ગુજરાત" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", region: "ಕರ್ನಾಟಕ" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", region: "ਪੰਜਾਬ" },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ", region: "ଓଡ଼ିଶା" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", region: "കേരളം" },
  { code: "ur", name: "Urdu", nativeName: "اردو", region: "قومی / تمام ریاستیں" },
  { code: "as", name: "Assamese", nativeName: "অসমীয়া", region: "অসম" },
];

export type LanguageCode = string;

// Translation dictionary
const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    // Nav Items
    "nav.profile": "Profile",
    "nav.budget": "Budget",
    "nav.leader": "Leader",
    "nav.infrastructure": "Infrastructure",
    "nav.bookmark": "Bookmark",
    "nav.settings": "Setting & Privacy",
    "nav.language": "Language",
    "nav.help": "Help Center",
    "nav.home": "Home",
    "nav.search": "Search",
    "nav.connect": "Connect",
    "nav.compose": "Post Issue",
    "nav.signOut": "Sign Out",
    "nav.signIn": "Sign In",
    "nav.theme": "Theme Preference",
    "nav.following": "Following",
    "nav.followers": "Followers",
    "nav.guest": "Guest Citizen",
    "nav.signInPrompt": "Sign in to track your grievances and access your verified profile.",
    "nav.signInBtn": "Sign In to Account",
    
    // Header
    "header.title": "Open Desh",
    "header.subtitle": "Civic Governance & Leader Accountability",
    "header.searchPlaceholder": "Search complaints, leaders, departments...",
    "header.postGrievance": "Post Grievance",
    
    // Bottom Navigation
    "bottom.home": "Home",
    "bottom.search": "Search",
    "bottom.post": "Post",
    "bottom.leader": "Leader",
    "bottom.budget": "Budget",

    // Feed & Compose
    "feed.kyaProblem": "What is the problem? (Kya Problem ha?)",
    "feed.reportIssue": "Report Public Grievance",
    "feed.forYou": "For You",
    "feed.following": "Following",
    "feed.allDepartments": "All Departments",
    "feed.upvote": "Upvote",
    "feed.comment": "Comment",
    "feed.share": "Share",
    "feed.sla": "SLA Deadline",
    "feed.underReview": "Under Review",
    "feed.actionTaken": "Action Taken",
    "feed.resolved": "Resolved",
    "feed.submitted": "Submitted",

    // Budget
    "budget.title": "Budget Ledger",
    "budget.inflowTab": "Revenue (Inflow)",
    "budget.outflowTab": "Expenditure (Outflow)",
    "budget.receipts": "Total Receipts (Revenue)",
    "budget.spending": "Total Expenditure (Spending)",
    "budget.capex": "Capital Infra (Capex)",

    // Evaluation & Rating Page
    "eval.headerTitle": "Performance Index",
    "eval.headerSubtitle": "Transparent. Verified. For You.",
    "eval.systemIndex": "SYSTEM INDEX",
    "eval.rateDepartment": "Rate Department",
    "eval.rateLeader": "Rate Leader",
    "eval.rateProfile": "Rate Profile",
    "eval.excellent": "Excellent",
    "eval.good": "Good",
    "eval.average": "Average",
    "eval.fair": "Fair",
    "eval.poor": "Poor",
    "eval.needsAudit": "Needs Audit",
    "eval.algorithmTitle": "100-Pt Algorithm",
    "eval.algorithmSubtitle": "Scientifically Weighted",
    "eval.publicReviews": "Public Reviews",
    "eval.reviewsCount": "Reviews",
    "eval.youRate": "You Rate",
    "eval.auditEngineTitle": "Deterministic 100-Point Civic Audit Engine",
    "eval.auditEngineDesc": "The System Score cannot be manually modified by any user or administrator. It is computed purely from statistical verification of Public Domain Government Gazettes, CAG Audits, and Geo-tagged SLA Logs.",
    "eval.dimensionsTitle": "Performance Evaluation Dimensions (Total: 100 Pts)",
    "eval.disclosuresTitle": "Public Domain Knowledge & Statutory Disclosures",
    "eval.disclosuresDesc": "All data points conform to open records under the Right to Information Act (RTI Section 4) and State Gazette publications.",
    "eval.publicRatingAverage": "Public Rating Average",
    "eval.basedOnReviews": "Based on {count} verified citizen evaluation(s)",
    "eval.editReview": "Edit Review",
    "eval.writeReview": "Write Review",
    "eval.verifiedVoter": "Verified Voter",
    "eval.replyAsOfficial": "Reply to this Citizen Review as Official Authority",
    "eval.typeOfficialResponse": "Type official response / acknowledgment to this citizen...",
    "eval.cancel": "Cancel",
    "eval.publishReply": "Publish Official Reply",
    "eval.noReviewsYet": "No citizen reviews submitted for this profile yet.",
    "eval.civicIntegrityGuarantee": "CIVIC INTEGRITY GUARANTEE",
    "eval.civicIntegrityDesc": "Your review will be directly recorded on the verified public registry. Please provide factual and constructive feedback.",
    "eval.yourRating": "Your Rating",
    "eval.tapStarToRate": "Tap a star to rate",
    "eval.detailedReviewTitle": "Detailed Citizen Performance Review",
    "eval.detailedReviewSubtitle": "Share your experience. The more detail, the greater the impact.",
    "eval.reviewPlaceholder": "Write your experience regarding constituency road maintenance, flood control, MLA accessibility, or statutory fund utilization...",
    "eval.pillarFactBased": "Fact Based",
    "eval.pillarFactBasedDesc": "Share real experiences",
    "eval.pillarImpactful": "Impactful",
    "eval.pillarImpactfulDesc": "Your review drives change",
    "eval.pillarVerified": "Verified",
    "eval.pillarVerifiedDesc": "100% authentic & transparent",
    "eval.pillarConstructive": "Constructive",
    "eval.pillarConstructiveDesc": "Feedback for better governance",
    "eval.submitting": "Recording on Public Registry...",
    "eval.published": "Review Published!",
    "eval.submitReview": "Submit Review",
    "eval.updateReview": "Update Review",

    // Language Modal
    "lang.selectTitle": "Select App Language",
    "lang.selectSubtitle": "Choose your preferred Indian language to navigate Open Desh.",
    "lang.searchPlaceholder": "Search Indian language (हिन्दी, বাংলা, தமிழ்...)",
    "lang.active": "Active",
    "lang.apply": "Apply Language",
  },
  hi: {
    // Nav Items
    "nav.profile": "प्रोफ़ाइल",
    "nav.budget": "बजट",
    "nav.leader": "नेता ट्रैकर",
    "nav.infrastructure": "इन्फ्रास्ट्रक्चर",
    "nav.bookmark": "बुकमार्क",
    "nav.settings": "सेटिंग व प्राइवेसी",
    "nav.language": "भाषा (Language)",
    "nav.help": "सहायता केंद्र",
    "nav.home": "होम",
    "nav.search": "खोजें",
    "nav.connect": "कनेक्ट",
    "nav.compose": "समस्या दर्ज करें",
    "nav.signOut": "लॉग आउट करें",
    "nav.signIn": "साइन इन करें",
    "nav.theme": "थीम प्राथमिकता",
    "nav.following": "फ़ॉलोइंग",
    "nav.followers": "फ़ॉलोअर्स",
    "nav.guest": "अतिथि नागरिक",
    "nav.signInPrompt": "अपनी शिकायतों को ट्रैक करने और सत्यापित प्रोफ़ाइल हेतु साइन इन करें।",
    "nav.signInBtn": "खाते में साइन इन करें",

    // Header
    "header.title": "ओपन देश",
    "header.subtitle": "नागरिक शासन एवं जननेता जवाबदेही",
    "header.searchPlaceholder": "शिकायतें, नेता, विभाग खोजें...",
    "header.postGrievance": "शिकायत दर्ज करें",

    // Bottom Navigation
    "bottom.home": "होम",
    "bottom.search": "खोजें",
    "bottom.post": "पोस्ट",
    "bottom.leader": "नेता",
    "bottom.budget": "बजट",

    // Feed & Compose
    "feed.kyaProblem": "क्या समस्या है? (Kya Problem ha?)",
    "feed.reportIssue": "सार्वजनिक शिकायत दर्ज करें",
    "feed.forYou": "आपके लिए",
    "feed.following": "फ़ॉलोइंग",
    "feed.allDepartments": "सभी विभाग",
    "feed.upvote": "समर्थन (Upvote)",
    "feed.comment": "टिप्पणी",
    "feed.share": "साझा करें",
    "feed.sla": "SLA समय सीमा",
    "feed.underReview": "समीक्षाधीन",
    "feed.actionTaken": "कार्रवाई जारी",
    "feed.resolved": "समाधानित",
    "feed.submitted": "दर्ज किया गया",

    // Budget
    "budget.title": "बजट लेजर",
    "budget.inflowTab": "राजस्व (इनफ्लो)",
    "budget.outflowTab": "व्यय (आउटफ्लो)",
    "budget.receipts": "कुल प्राप्तियां (राजस्व)",
    "budget.spending": "कुल खर्चा (व्यय)",
    "budget.capex": "पूंजीगत विकास (Capex)",

    // Evaluation & Rating Page
    "eval.headerTitle": "परफॉरमेंस इंडेक्स",
    "eval.headerSubtitle": "पारदर्शी। सत्यापित। आपके लिए।",
    "eval.systemIndex": "सिस्टम इंडेक्स",
    "eval.rateDepartment": "विभाग को रेटिंग दें",
    "eval.rateLeader": "नेता को रेटिंग दें",
    "eval.rateProfile": "प्रोफ़ाइल को रेटिंग दें",
    "eval.excellent": "उत्कृष्ट (Excellent)",
    "eval.good": "अच्छा (Good)",
    "eval.average": "औसत (Average)",
    "eval.fair": "सामान्य (Fair)",
    "eval.poor": "खराब (Poor)",
    "eval.needsAudit": "ऑडिट आवश्यक",
    "eval.algorithmTitle": "100-Pt एल्गोरिथ्म",
    "eval.algorithmSubtitle": "वैज्ञानिक गणना आधारित",
    "eval.publicReviews": "जनता की समीक्षाएं",
    "eval.reviewsCount": "समीक्षाएं",
    "eval.youRate": "आपकी रेटिंग",
    "eval.auditEngineTitle": "100-अंकीय नागरिक ऑडिट इंजन",
    "eval.auditEngineDesc": "सिस्टम स्कोर किसी व्यक्ति या व्यवस्थापक द्वारा बदला नहीं जा सकता। यह पूरी तरह से सरकारी गजट, सीएजी ऑडिट और जीपीएस-सत्यापित एसएलए लॉग्स पर आधारित है।",
    "eval.dimensionsTitle": "प्रदर्शन मूल्यांकन मानक (कुल: 100 अंक)",
    "eval.disclosuresTitle": "सार्वजनिक प्रकटीकरण एवं आरटीआई रिकॉर्ड",
    "eval.disclosuresDesc": "सभी आंकड़े सूचना का अधिकार अधिनियम (धारा 4) एवं राज्य विधानसभा गजट के सार्वजनिक रिकॉर्ड्स के अनुरूप हैं।",
    "eval.publicRatingAverage": "जनता की औसत रेटिंग",
    "eval.basedOnReviews": "{count} सत्यापित नागरिक समीक्षाओं पर आधारित",
    "eval.editReview": "समीक्षा संपादित करें",
    "eval.writeReview": "समीक्षा लिखें",
    "eval.verifiedVoter": "सत्यापित मतदाता",
    "eval.replyAsOfficial": "आधिकारिक प्राधिकारी के रूप में उत्तर दें",
    "eval.typeOfficialResponse": "इस नागरिक समीक्षा पर आधिकारिक उत्तर / संज्ञान लिखें...",
    "eval.cancel": "रद्द करें",
    "eval.publishReply": "आधिकारिक उत्तर प्रकाशित करें",
    "eval.noReviewsYet": "इस प्रोफ़ाइल पर अभी तक कोई समीक्षा दर्ज नहीं की गई है।",
    "eval.civicIntegrityGuarantee": "नागरिक अखंडता गारंटी",
    "eval.civicIntegrityDesc": "आपकी समीक्षा सीधे सत्यापित सार्वजनिक रजिस्ट्री पर दर्ज होगी। कृपया तथ्यपरक और रचनात्मक प्रतिक्रिया दें।",
    "eval.yourRating": "आपकी रेटिंग",
    "eval.tapStarToRate": "रेटिंग देने के लिए स्टार पर टैप करें",
    "eval.detailedReviewTitle": "विस्तृत नागरिक प्रदर्शन समीक्षा",
    "eval.detailedReviewSubtitle": "अपना अनुभव साझा करें। जितनी विस्तृत जानकारी होगी, उतना बड़ा प्रभाव पड़ेगा।",
    "eval.reviewPlaceholder": "सड़क रखरखाव, बाढ़ नियंत्रण, विधायक उपलब्धता अथवा विकास निधि उपयोग पर अपना अनुभव लिखें...",
    "eval.pillarFactBased": "तथ्य आधारित",
    "eval.pillarFactBasedDesc": "वास्तविक अनुभव साझा करें",
    "eval.pillarImpactful": "प्रभावशाली",
    "eval.pillarImpactfulDesc": "आपकी समीक्षा बदलाव लाती है",
    "eval.pillarVerified": "सत्यापित",
    "eval.pillarVerifiedDesc": "100% प्रामाणिक व पारदर्शी",
    "eval.pillarConstructive": "रचनात्मक",
    "eval.pillarConstructiveDesc": "बेहतर शासन हेतु प्रतिक्रिया",
    "eval.submitting": "पब्लिक रजिस्ट्री पर दर्ज हो रहा है...",
    "eval.published": "समीक्षा प्रकाशित हो गई!",
    "eval.submitReview": "समीक्षा सबमिट करें",
    "eval.updateReview": "समीक्षा अपडेट करें",

    // Language Modal
    "lang.selectTitle": "ऐप की भाषा चुनें",
    "lang.selectSubtitle": "ओपन देश चलाने के लिए अपनी पसंदीदा भारतीय भाषा चुनें।",
    "lang.searchPlaceholder": "भारतीय भाषा खोजें (हिन्दी, বাংলা, தமிழ்...)",
    "lang.active": "सक्रिय",
    "lang.apply": "भाषा लागू करें",
  },
  bn: {
    "nav.profile": "প্রোফাইল",
    "nav.budget": "বাজেট",
    "nav.leader": "জননেতা ট্র্যাকার",
    "nav.infrastructure": "পরিকাঠামো",
    "nav.bookmark": "বুকমার্ক",
    "nav.settings": "সেটিংস ও গোপনীয়তা",
    "nav.language": "ভাষা (Language)",
    "nav.help": "সহায়তা কেন্দ্র",
    "nav.home": "হোম",
    "nav.search": "অনুসন্ধান",
    "nav.connect": "সংযোগ",
    "nav.compose": "অভিযোগ জানান",
    "nav.signOut": "লগ আউট",
    "nav.signIn": "লগ ইন",
    "nav.theme": "থিম পছন্দ",
    "nav.following": "অনুসরণ করছেন",
    "nav.followers": "অনুসারী",
    "nav.guest": "অতিথি নাগরিক",
    "nav.signInPrompt": "আপনার অভিযোগ ট্র্যাক করতে লগ ইন করুন।",
    "nav.signInBtn": "অ্যাকাউন্টে লগ ইন করুন",
    "header.title": "ওপেন দেশ",
    "header.subtitle": "নাগরিক শাসন ও নেতৃত্ব দায়বদ্ধতা",
    "header.searchPlaceholder": "অভিযোগ, নেতা, বিভাগ খুঁজুন...",
    "header.postGrievance": "অভিযোগ পোস্ট করুন",
    "bottom.home": "হোম",
    "bottom.search": "অনুসন্ধান",
    "bottom.post": "পোস্ট",
    "bottom.leader": "নেতা",
    "bottom.infra": "ইনফ্রা",
    "feed.kyaProblem": "কী সমস্যা হয়েছে?",
    "feed.reportIssue": "জনসাধারণের অভিযোগ রিপোর্ট করুন",
    "feed.forYou": "আপনার জন্য",
    "feed.following": "অনুসরণ",
    "feed.allDepartments": "সকল বিভাগ",
    "feed.upvote": "সমর্থন",
    "feed.comment": "মন্তব্য",
    "feed.share": "শেয়ার",
    "feed.sla": "SLA সময়সীমা",
    "feed.underReview": "পর্যালোচনাধীন",
    "feed.actionTaken": "ব্যবস্থা নেওয়া হচ্ছে",
    "feed.resolved": "সমাধান হয়েছে",
    "feed.submitted": "জমা দেওয়া হয়েছে",
    "budget.title": "বাজেট লেজার",
    "budget.inflowTab": "রাজস্ব (আয়)",
    "budget.outflowTab": "ব্যয় (খরচ)",
    "budget.receipts": "মোট আয়",
    "budget.spending": "মোট ব্যয়",
    "budget.capex": "মূলধনী ব্যয় (Capex)",
    "lang.selectTitle": "অ্যাপের ভাষা নির্বাচন করুন",
    "lang.selectSubtitle": "আপনার পছন্দের ভারতীয় ভাষা বেছে নিন।",
    "lang.searchPlaceholder": "ভাষা খুঁজুন...",
    "lang.active": "সক্রিয়",
    "lang.apply": "ভাষা প্রয়োগ করুন",
  },
  mr: {
    "nav.profile": "प्रोफाइल",
    "nav.budget": "अर्थसंकल्प",
    "nav.leader": "लोकप्रतिनिधी",
    "nav.infrastructure": "पायाभूत सुविधा",
    "nav.bookmark": "बुकमार्क",
    "nav.settings": "सेटिंग्ज आणि गोपनीयता",
    "nav.language": "भाषा (Language)",
    "nav.help": "मदत केंद्र",
    "nav.home": "मुख्यपृष्ठ",
    "nav.search": "शोधा",
    "nav.connect": "जोडा",
    "nav.compose": "तक्रार नोंदवा",
    "nav.signOut": "बाहेर पडा",
    "nav.signIn": "साइन इन करा",
    "nav.theme": "थीम प्राधान्य",
    "nav.following": "फॉलो करत आहात",
    "nav.followers": "फॉलोअर्स",
    "nav.guest": "अतिथी नागरिक",
    "nav.signInPrompt": "आपल्या तक्रारींचा मागोवा घेण्यासाठी साइन इन करा.",
    "nav.signInBtn": "खात्यात साइन इन करा",
    "header.title": "ओपन देश",
    "header.subtitle": "नागरी सुशासन आणि उत्तरदायित्व",
    "header.searchPlaceholder": "तक्रारी, नेते, विभाग शोधा...",
    "header.postGrievance": "तक्रार नोंदवा",
    "bottom.home": "होम",
    "bottom.search": "शोधा",
    "bottom.post": "पोस्ट",
    "bottom.leader": "नेते",
    "bottom.infra": "इन्फ्रा",
    "feed.kyaProblem": "काय अडचण आहे?",
    "feed.reportIssue": "सार्वजनिक तक्रार नोंदवा",
    "feed.forYou": "तुमच्यासाठी",
    "feed.following": "फॉलो करत असलेले",
    "feed.allDepartments": "सर्व विभाग",
    "feed.upvote": "समर्थन",
    "feed.comment": "प्रतिक्रिया",
    "feed.share": "शेअर",
    "feed.sla": "SLA मुदत",
    "feed.underReview": "पुनरावलोकनात",
    "feed.actionTaken": "कारवाई चालू",
    "feed.resolved": "निवारण झाले",
    "feed.submitted": "नोंदवले गेले",
    "budget.title": "अर्थसंकल्प लेजर",
    "budget.inflowTab": "महसूल (आवक)",
    "budget.outflowTab": "खर्च (जावक)",
    "budget.receipts": "एकूण महसूल",
    "budget.spending": "एकूण खर्च",
    "budget.capex": "भांडवली खर्च (Capex)",
    "lang.selectTitle": "अ‍ॅपची भाषा निवडा",
    "lang.selectSubtitle": "आपली पसंतीची भारतीय भाषा निवडा.",
    "lang.searchPlaceholder": "भाषा शोधा...",
    "lang.active": "सक्रिय",
    "lang.apply": "भाषा लागू करा",
  },
  te: {
    "nav.profile": "ప్రొఫైల్",
    "nav.budget": "బడ్జెట్",
    "nav.leader": "నాయకుల ట్రాకర్",
    "nav.infrastructure": "మౌలిక సదుపాయాలు",
    "nav.bookmark": "బుక్‌మార్క్‌లు",
    "nav.settings": "సెట్టింగ్‌లు & గోప్యత",
    "nav.language": "భాష (Language)",
    "nav.help": "సహాయ కేంద్రం",
    "nav.home": "హోమ్",
    "nav.search": "శోధన",
    "nav.connect": "కనెక్ట్",
    "nav.compose": "ఫిర్యాదు నమోదు",
    "nav.signOut": "సైన్ అవుట్",
    "nav.signIn": "సైన్ ఇన్",
    "nav.theme": "థీమ్ ప్రాధాన్యత",
    "nav.following": "ఫాలో అవుతున్నారు",
    "nav.followers": "ఫాలోవర్స్",
    "nav.guest": "అతిథి పౌరుడు",
    "nav.signInPrompt": "మీ ఫిర్యాదులను ట్రాక్ చేయడానికి సైన్ ఇన్ చేయండి.",
    "nav.signInBtn": "ఖాతాలోకి సైన్ ఇన్ చేయండి",
    "header.title": "ఓపెన్ దేశ్",
    "header.subtitle": "పౌర పాలన & నాయకుల జవాబుదారీతనం",
    "header.searchPlaceholder": "ఫిర్యాదులు, నాయకులు, శాఖలను శోధించండి...",
    "header.postGrievance": "ఫిర్యాదు చేయండి",
    "bottom.home": "హోమ్",
    "bottom.search": "శోధన",
    "bottom.post": "పోస్ట్",
    "bottom.leader": "నాయకుడు",
    "bottom.infra": "ఇన్ఫ్రా",
    "feed.kyaProblem": "ఏమి సమస్య ఉంది?",
    "feed.reportIssue": "ప్రజా సమస్యను నివేదించండి",
    "feed.forYou": "మీ కోసం",
    "feed.following": "ఫాలోయింగ్",
    "feed.allDepartments": "అన్ని విభాగాలు",
    "feed.upvote": "మద్దతు (Upvote)",
    "feed.comment": "వ్యాఖ్య",
    "feed.share": "షేర్",
    "feed.sla": "SLA గడువు",
    "feed.underReview": "పరిశీలనలో ఉంది",
    "feed.actionTaken": "చర్య ప్రారంభమైంది",
    "feed.resolved": "పరిష్కరించబడింది",
    "feed.submitted": "సమర్పించబడింది",
    "budget.title": "బడ్జెట్ లెడ్జర్",
    "budget.inflowTab": "ఆదాయం (Inflow)",
    "budget.outflowTab": "వ్యయం (Outflow)",
    "budget.receipts": "మొత్తం రాబడి",
    "budget.spending": "మొత్తం ఖర్చు",
    "budget.capex": "మూలధన వ్యయం (Capex)",
    "lang.selectTitle": "యాప్ భాషను ఎంచుకోండి",
    "lang.selectSubtitle": "మీ ప్రాధాన్యత గల భారతీయ భాషను ఎంచుకోండి.",
    "lang.searchPlaceholder": "భాషను శోధించండి...",
    "lang.active": "సక్రియం",
    "lang.apply": "భాషను వర్తింపజేయండి",
  },
  ta: {
    "nav.profile": "சுயவிவரம்",
    "nav.budget": "பட்ஜெட்",
    "nav.leader": "மக்கள் தலைவர்",
    "nav.infrastructure": "உள்கட்டமைப்பு",
    "nav.bookmark": "புக்மார்க்",
    "nav.settings": "அமைப்புகள் & தனியுரிமை",
    "nav.language": "மொழி (Language)",
    "nav.help": "உதவி மையம்",
    "nav.home": "முகப்பு",
    "nav.search": "தேடுக",
    "nav.connect": "இணைப்பு",
    "nav.compose": "புகார் பதிவு",
    "nav.signOut": "வெளியேறு",
    "nav.signIn": "உள்நுழைக",
    "nav.theme": "விருப்ப தீம்",
    "nav.following": "பின்தொடர்பவை",
    "nav.followers": "பின்தொடர்பவர்கள்",
    "nav.guest": "விருந்தினர் குடிமகன்",
    "nav.signInPrompt": "உங்கள் புகார்களைக் கண்காணிக்க உள்நுழையவும்.",
    "nav.signInBtn": "கணக்கில் உள்நுழைக",
    "header.title": "ஓபன் தேஷ்",
    "header.subtitle": "குடிமக்கள் நிர்வாகம் மற்றும் பொறுப்புடைமை",
    "header.searchPlaceholder": "புகார்கள், தலைவர்கள், துறைகளைத் தேடுங்கள்...",
    "header.postGrievance": "புகார் இடுக",
    "bottom.home": "முகப்பு",
    "bottom.search": "தேடு",
    "bottom.post": "பதிவு",
    "bottom.leader": "தலைவர்",
    "bottom.infra": "கட்டமைப்பு",
    "feed.kyaProblem": "என்ன பிரச்சனை?",
    "feed.reportIssue": "பொதுப் புகாரைப் பதிவு செய்யவும்",
    "feed.forYou": "உங்களுக்காக",
    "feed.following": "பின்தொடர்பவை",
    "feed.allDepartments": "அனைத்துத் துறைகள்",
    "feed.upvote": "ஆதரவு (Upvote)",
    "feed.comment": "கருத்து",
    "feed.share": "பகிர்",
    "feed.sla": "SLA காலக்கெடு",
    "feed.underReview": "பரிசீலனையில்",
    "feed.actionTaken": "நடவடிக்கை எடுக்கப்படுகிறது",
    "feed.resolved": "தீர்க்கப்பட்டது",
    "feed.submitted": "சமர்ப்பிக்கப்பட்டது",
    "budget.title": "பட்ஜெட் லெட்ஜர்",
    "budget.inflowTab": "வருவாய் (Inflow)",
    "budget.outflowTab": "செலவினம் (Outflow)",
    "budget.receipts": "மொத்த வருவாய்",
    "budget.spending": "மொத்த செலவு",
    "budget.capex": "மூலதன உள்கட்டமைப்பு (Capex)",
    "lang.selectTitle": "செயலி மொழியைத் தேர்ந்தெடுக்கவும்",
    "lang.selectSubtitle": "உங்கள் விருப்பமான இந்திய மொழியைத் தேர்வுசெய்க.",
    "lang.searchPlaceholder": "மொழியைத் தேடுங்கள்...",
    "lang.active": "செயலில் உள்ளது",
    "lang.apply": "மொழியைப் பயன்படுத்து",
  },
  gu: {
    "nav.profile": "પ્રોફાઇલ",
    "nav.budget": "બજેટ",
    "nav.leader": "નેતા ટ્રેકર",
    "nav.infrastructure": "ઇન્ફ્રાસ્ટ્રક્ચર",
    "nav.bookmark": "બુકમાર્ક",
    "nav.settings": "સેટિંગ્સ અને પ્રાઇવસી",
    "nav.language": "ભાષા (Language)",
    "nav.help": "મદદ કેન્દ્ર",
    "nav.home": "હોમ",
    "nav.search": "શોધો",
    "nav.connect": "કનેક્ટ",
    "nav.compose": "ફરિયાદ નોંધાવો",
    "nav.signOut": "લૉગ આઉટ",
    "nav.signIn": "સાઇન ઇન",
    "nav.theme": "થીમ પસંદગી",
    "nav.following": "ફોલોઇંગ",
    "nav.followers": "ફોલોઅર્સ",
    "nav.guest": "મહેમાન નાગરિક",
    "nav.signInPrompt": "તમારી ફરિયાદો ટ્રેક કરવા સાઇન ઇન કરો.",
    "nav.signInBtn": "ખાતામાં સાઇન ઇન કરો",
    "header.title": "ઓપન દેશ",
    "header.subtitle": "નાગરિક શાસન અને નેતા ઉત્તરદાયિત્વ",
    "header.searchPlaceholder": "ફરિયાદો, નેતાઓ, વિભાગો શોધો...",
    "header.postGrievance": "ફરિયાદ પોસ્ટ કરો",
    "bottom.home": "હોમ",
    "bottom.search": "શોધો",
    "bottom.post": "પોસ્ટ",
    "bottom.leader": "નેતા",
    "bottom.infra": "ઇન્ફ્રા",
    "feed.kyaProblem": "શું સમસ્યા છે?",
    "feed.reportIssue": "જાહેર ફરિયાદ નોંધાવો",
    "feed.forYou": "તમારા માટે",
    "feed.following": "ફોલોઇંગ",
    "feed.allDepartments": "બધા વિભાગો",
    "feed.upvote": "સમર્થન",
    "feed.comment": "ટિપ્પણી",
    "feed.share": "શેર",
    "feed.sla": "SLA સમયમર્યાદા",
    "feed.underReview": "સમીક્ષા હેઠળ",
    "feed.actionTaken": "કાર્યવાહી શરૂ",
    "feed.resolved": "ઉકેલાઈ ગયું",
    "feed.submitted": "દાખલ કરવામાં આવ્યું",
    "budget.title": "બજેટ લેજર",
    "budget.inflowTab": "આવક (Inflow)",
    "budget.outflowTab": "ખર્ચ (Outflow)",
    "budget.receipts": "કુલ આવક",
    "budget.spending": "કુલ ખર્ચ",
    "budget.capex": "મૂડી ખર્ચ (Capex)",
    "lang.selectTitle": "એપની ભાષા પસંદ કરો",
    "lang.selectSubtitle": "તમારી પસંદગીની ભારતીય ભાષા પસંદ કરો.",
    "lang.searchPlaceholder": "ભાષા શોધો...",
    "lang.active": "સક્રિય",
    "lang.apply": "ભાષા લાગુ કરો",
  },
  kn: {
    "nav.profile": "ಪ್ರೊಫೈಲ್",
    "nav.budget": "ಬಜೆಟ್",
    "nav.leader": "ನಾಯಕ ಟ್ರ್ಯಾಕರ್",
    "nav.infrastructure": "ಮೂಲಸೌಕರ್ಯ",
    "nav.bookmark": "ಬುಕ್‌ಮಾರ್ಕ್",
    "nav.settings": "ಸೆಟ್ಟಿಂಗ್ಸ್ ಮತ್ತು ಗೌಪ್ಯತೆ",
    "nav.language": "ಭಾಷೆ (Language)",
    "nav.help": "ಸಹಾಯ ಕೇಂದ್ರ",
    "nav.home": "ಮುಖಪುಟ",
    "nav.search": "ಹುಡುಕಿ",
    "nav.connect": "ಸಂಪರ್ಕ",
    "nav.compose": "ದೂರು ದಾಖಲಿಸಿ",
    "nav.signOut": "ಸೈನ್ ಔಟ್",
    "nav.signIn": "ಸೈನ್ ಇನ್",
    "nav.theme": "ಥೀಮ್ ಆದ್ಯತೆ",
    "nav.following": "ಫಾಲೋಯಿಂಗ್",
    "nav.followers": "ಫಾಲೋವರ್ಸ್",
    "nav.guest": "ಅತಿಥಿ ನಾಗರಿಕ",
    "nav.signInPrompt": "ನಿಮ್ಮ ದೂರುಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    "nav.signInBtn": "ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ",
    "header.title": "ಓಪನ್ ದೇಶ್",
    "header.subtitle": "ನಾಗರಿಕ ಆಡಳಿತ ಮತ್ತು ನಾಯಕರ ಹೊಣೆಗಾರಿಕೆ",
    "header.searchPlaceholder": "ದೂರುಗಳು, ನಾಯಕರು, ಇಲಾಖೆಗಳನ್ನು ಹುಡುಕಿ...",
    "header.postGrievance": "ದೂರು ದಾಖಲಿಸಿ",
    "bottom.home": "ಮುಖಪುಟ",
    "bottom.search": "ಹುಡುಕಿ",
    "bottom.post": "ಪೋಸ್ಟ್",
    "bottom.leader": "ನಾಯಕ",
    "bottom.infra": "ಇನ್ಫ್ರಾ",
    "feed.kyaProblem": "ಏನು ಸಮಸ್ಯೆ ಇದೆ?",
    "feed.reportIssue": "ಸಾರ್ವಜನಿಕ ದೂರನ್ನು ವರದಿ ಮಾಡಿ",
    "feed.forYou": "ನಿಮಗಾಗಿ",
    "feed.following": "ಫಾಲೋಯಿಂಗ್",
    "feed.allDepartments": "ಎಲ್ಲಾ ಇಲಾಖೆಗಳು",
    "feed.upvote": "ಬೆಂಬಲ (Upvote)",
    "feed.comment": "ಕಾಮೆಂಟ್",
    "feed.share": "ಹಂಚಿಕೊಳ್ಳಿ",
    "feed.sla": "SLA ಗಡುವು",
    "feed.underReview": "ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ",
    "feed.actionTaken": "ಕ್ರಮ ಕೈಗೊಳ್ಳಲಾಗಿದೆ",
    "feed.resolved": "ಪರಿಹರಿಸಲಾಗಿದೆ",
    "feed.submitted": "ಸಲ್ಲಿಸಲಾಗಿದೆ",
    "budget.title": "ಬಜೆಟ್ ಲೆಡ್ಜರ್",
    "budget.inflowTab": "ಆದಾಯ (Inflow)",
    "budget.outflowTab": "ವೆಚ್ಚ (Outflow)",
    "budget.receipts": "ಒಟ್ಟು ಆದಾಯ",
    "budget.spending": "ಒಟ್ಟು ವೆಚ್ಚ",
    "budget.capex": "ಬಂಡವಾಳ ವೆಚ್ಚ (Capex)",
    "lang.selectTitle": "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "lang.selectSubtitle": "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾರತೀಯ ಭಾಷೆಯನ್ನು ಆರಿಸಿ.",
    "lang.searchPlaceholder": "ಭಾಷೆ ಹುಡುಕಿ...",
    "lang.active": "ಸಕ್ರಿಯ",
    "lang.apply": "ಭಾಷೆ ಅನ್ವಯಿಸಿ",
  },
  pa: {
    "nav.profile": "ਪ੍ਰੋਫਾਈਲ",
    "nav.budget": "ਬਜਟ",
    "nav.leader": "ਨੇਤਾ ਟਰੈਕਰ",
    "nav.infrastructure": "ਬੁਨਿਆਦੀ ਢਾਂਚਾ",
    "nav.bookmark": "ਬੁੱਕਮਾਰਕ",
    "nav.settings": "ਸੈਟਿੰਗਾਂ ਅਤੇ ਗੋਪਨੀਯਤਾ",
    "nav.language": "ਭਾਸ਼ਾ (Language)",
    "nav.help": "ਸਹਾਇਤਾ ਕੇਂਦਰ",
    "nav.home": "ਹੋਮ",
    "nav.search": "ਖੋਜ",
    "nav.connect": "ਕਨੈਕਟ",
    "nav.compose": "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
    "nav.signOut": "ਸਾਈਨ ਆਉਟ",
    "nav.signIn": "ਸਾਈਨ ਇਨ",
    "nav.theme": "ਥੀਮ ਤਰਜੀਹ",
    "nav.following": "ਫਾਲੋਇੰਗ",
    "nav.followers": "ਫਾਲੋਅਰਜ਼",
    "nav.guest": "ਮਹਿਮਾਨ ਨਾਗਰਿਕ",
    "nav.signInPrompt": "ਆਪਣੀਆਂ ਸ਼ਿਕਾਇਤਾਂ ਨੂੰ ਟਰੈਕ ਕਰਨ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।",
    "nav.signInBtn": "ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ",
    "header.title": "ਓਪਨ ਦੇਸ਼",
    "header.subtitle": "ਨਾਗਰਿਕ ਪ੍ਰਸ਼ਾਸਨ ਅਤੇ ਨੇਤਾ ਜਵਾਬਦੇਹੀ",
    "header.searchPlaceholder": "ਸ਼ਿਕਾਇਤਾਂ, ਨੇਤਾ, ਵਿਭਾਗ ਲੱਭੋ...",
    "header.postGrievance": "ਸ਼ਿਕਾਇਤ ਪੋਸਟ ਕਰੋ",
    "bottom.home": "ਹੋਮ",
    "bottom.search": "ਖੋਜ",
    "bottom.post": "ਪੋਸਟ",
    "bottom.leader": "ਨੇਤਾ",
    "bottom.infra": "ਇਨਫ੍ਰਾ",
    "feed.kyaProblem": "ਕੀ ਸਮੱਸਿਆ ਹੈ?",
    "feed.reportIssue": "ਜਨਤਕ ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
    "feed.forYou": "ਤੁਹਾਡੇ ਲਈ",
    "feed.following": "ਫਾਲੋਇੰਗ",
    "feed.allDepartments": "ਸਾਰੇ ਵਿਭਾਗ",
    "feed.upvote": "ਸਮਰਥਨ",
    "feed.comment": "ਟਿੱਪਣੀ",
    "feed.share": "ਸਾਂਝਾ ਕਰੋ",
    "feed.sla": "SLA ਸਮਾਂ ਸੀਮਾ",
    "feed.underReview": "ਸਮੀਖਿਆ ਅਧੀਨ",
    "feed.actionTaken": "ਕਾਰਵਾਈ ਜਾਰੀ",
    "feed.resolved": "ਹੱਲ ਕੀਤਾ ਗਿਆ",
    "feed.submitted": "ਦਰਜ ਕੀਤੀ ਗਈ",
    "budget.title": "ਬਜਟ ਲੇਜ਼ਰ",
    "budget.inflowTab": "ਆਮਦਨ (Inflow)",
    "budget.outflowTab": "ਖਰਚਾ (Outflow)",
    "budget.receipts": "ਕੁੱਲ ਆਮਦਨ",
    "budget.spending": "ਕੁੱਲ ਖਰਚਾ",
    "budget.capex": "ਪੂੰਜੀ ਖਰਚ (Capex)",
    "lang.selectTitle": "ਐਪ ਭਾਸ਼ਾ ਚੁਣੋ",
    "lang.selectSubtitle": "ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਰਤੀ ਭਾਸ਼ਾ ਚੁਣੋ।",
    "lang.searchPlaceholder": "ਭਾਸ਼ਾ ਖੋਜੋ...",
    "lang.active": "ਸਰਗਰਮ",
    "lang.apply": "ਭਾਸ਼ਾ ਲਾਗੂ ਕਰੋ",
  },
  or: {
    "nav.profile": "ପ୍ରୋଫାଇଲ୍",
    "nav.budget": "ବଜେଟ୍",
    "nav.leader": "ନେତା ଟ୍ରାକର୍",
    "nav.infrastructure": "ଭିତ୍ତିଭୂମି",
    "nav.bookmark": "ବୁକମାର୍କ",
    "nav.settings": "ସେଟିଂସ ଓ ଗୋପନୀୟତା",
    "nav.language": "ଭାଷା (Language)",
    "nav.help": "ସହାୟତା କେନ୍ଦ୍ର",
    "nav.home": "ହୋମ୍",
    "nav.search": "ସନ୍ଧାନ",
    "nav.connect": "ସଂଯୋଗ",
    "nav.compose": "ଅଭିଯୋଗ ଦାଖଲ",
    "nav.signOut": "ସାଇନ୍ ଆଉଟ୍",
    "nav.signIn": "ସାଇନ୍ ଇନ୍",
    "nav.theme": "ଥିମ୍ ପସନ୍ଦ",
    "nav.following": "ଫଲୋଇଂ",
    "nav.followers": "ଫଲୋଅର୍ସ",
    "nav.guest": "ଅତିଥି ନାଗରିକ",
    "nav.signInPrompt": "ଆପଣଙ୍କ ଅଭିଯୋଗ ଟ୍ରାକ୍ କରିବାକୁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ।",
    "nav.signInBtn": "ଖାତାରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ",
    "header.title": "ଓପନ ଦେଶ",
    "header.subtitle": "ନାଗରିକ ପ୍ରଶାସନ ଓ ନେତୃତ୍ୱ ଉତ୍ତରଦାୟିତ୍ୱ",
    "header.searchPlaceholder": "ଅଭିଯୋଗ, ନେତା, ବିଭାଗ ଖୋଜନ୍ତୁ...",
    "header.postGrievance": "ଅଭିଯୋଗ ପୋଷ୍ଟ କରନ୍ତୁ",
    "bottom.home": "ହୋମ୍",
    "bottom.search": "ଖୋଜନ୍ତୁ",
    "bottom.post": "ପୋଷ୍ଟ",
    "bottom.leader": "ନେତା",
    "bottom.infra": "ଇନଫ୍ରା",
    "feed.kyaProblem": "କଣ ସମସ୍ୟା ରହିଛି?",
    "feed.reportIssue": "ସାଧାରଣ ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
    "feed.forYou": "ଆପଣଙ୍କ ପାଇଁ",
    "feed.following": "ଫଲୋଇଂ",
    "feed.allDepartments": "ସମସ୍ତ ବିଭାଗ",
    "feed.upvote": "ସମର୍ଥନ",
    "feed.comment": "ମନ୍ତବ୍ୟ",
    "feed.share": "ସେୟାର",
    "feed.sla": "SLA ସମୟସୀମା",
    "feed.underReview": "ସମୀକ୍ଷାଧୀନ",
    "feed.actionTaken": "ପଦକ୍ଷେପ ନିଆଯାଉଛି",
    "feed.resolved": "ସମାଧାନ ହୋଇଛି",
    "feed.submitted": "ଦାଖଲ ହୋଇଛି",
    "budget.title": "ବଜେଟ୍ ଲେଜର",
    "budget.inflowTab": "ରାଜସ୍ୱ (Inflow)",
    "budget.outflowTab": "ଖର୍ଚ୍ଚ (Outflow)",
    "budget.receipts": "ମୋଟ ଆୟ",
    "budget.spending": "ମୋଟ ଖର୍ଚ୍ଚ",
    "budget.capex": "ପୁଞ୍ଜି ବ୍ୟୟ (Capex)",
    "lang.selectTitle": "ଆପ୍ ଭାଷା ବାଛନ୍ତୁ",
    "lang.selectSubtitle": "ଆପଣଙ୍କ ପସନ୍ଦର ଭାରତୀୟ ଭାଷା ବାଛନ୍ତୁ।",
    "lang.searchPlaceholder": "ଭାଷା ଖୋଜନ୍ତୁ...",
    "lang.active": "ସକ୍ରିୟ",
    "lang.apply": "ଭାଷା ଲାଗୁ କରନ୍ତୁ",
  },
  ml: {
    "nav.profile": "പ്രൊഫൈൽ",
    "nav.budget": "ബജറ്റ്",
    "nav.leader": "നേതാവ് ട്രാക്കർ",
    "nav.infrastructure": "അടിസ്ഥാന സൗകര്യം",
    "nav.bookmark": "ബുക്ക്മാർക്ക്",
    "nav.settings": "ക്രമീകരണങ്ങളും സ്വകാര്യതയും",
    "nav.language": "ഭാഷ (Language)",
    "nav.help": "സഹായ കേന്ദ്രം",
    "nav.home": "ഹോം",
    "nav.search": "തിരയുക",
    "nav.connect": "കണക്റ്റ്",
    "nav.compose": "പരാതി നൽകുക",
    "nav.signOut": "സൈൻ ഔട്ട്",
    "nav.signIn": "സൈൻ ഇൻ",
    "nav.theme": "തീം മുൻഗണന",
    "nav.following": "ഫോളോ ചെയ്യുന്നു",
    "nav.followers": "ഫോളോവേഴ്‌സ്",
    "nav.guest": "അതിഥി പൗരൻ",
    "nav.signInPrompt": "പരാതികൾ ട്രാക്ക് ചെയ്യാൻ സൈൻ ഇൻ ചെയ്യുക.",
    "nav.signInBtn": "അക്കൗണ്ടിൽ സൈൻ ഇൻ ചെയ്യുക",
    "header.title": "ഓപ്പൺ ദേശ്",
    "header.subtitle": "പൗര ഭരണവും ഉത്തരവാദിത്തവും",
    "header.searchPlaceholder": "പരാതികൾ, നേതാക്കൾ, വകുപ്പുകൾ...",
    "header.postGrievance": "പരാതി പോസ്റ്റ് ചെയ്യുക",
    "bottom.home": "ഹോം",
    "bottom.search": "തിരയുക",
    "bottom.post": "പോസ്റ്റ്",
    "bottom.leader": "നേതാവ്",
    "bottom.infra": "ഇൻഫ്രാ",
    "feed.kyaProblem": "എന്താണ് പ്രശ്നം?",
    "feed.reportIssue": "പൊതു പരാതി അറിയിക്കുക",
    "feed.forYou": "നിങ്ങൾക്കായി",
    "feed.following": "ഫോളോയിംഗ്",
    "feed.allDepartments": "എല്ലാ വകുപ്പുകളും",
    "feed.upvote": "പിന്തുണ",
    "feed.comment": "അഭിപ്രായം",
    "feed.share": "പങ്കിടുക",
    "feed.sla": "SLA സമയപരിധി",
    "feed.underReview": "പരിശോധനയിൽ",
    "feed.actionTaken": "നടപടി ആരംഭിച്ചു",
    "feed.resolved": "പരിഹരിച്ചു",
    "feed.submitted": "സമർപ്പിച്ചു",
    "budget.title": "ബജറ്റ് ലെഡ്ജർ",
    "budget.inflowTab": "വരുമാനം (Inflow)",
    "budget.outflowTab": "ചെലവ് (Outflow)",
    "budget.receipts": "ആകെ വരുമാനം",
    "budget.spending": "ആകെ ചെലവ്",
    "budget.capex": "മൂലധന ചെലവ് (Capex)",
    "lang.selectTitle": "ആപ്പ് ഭാഷ തിരഞ്ഞെടുക്കുക",
    "lang.selectSubtitle": "നിങ്ങളുടെ മുൻഗണനയുള്ള ഇന്ത്യൻ ഭാഷ തിരഞ്ഞെടുക്കുക.",
    "lang.searchPlaceholder": "ഭാഷ തിരയുക...",
    "lang.active": "സജീവം",
    "lang.apply": "ഭാഷ പ്രയോഗിക്കുക",
  },
  ur: {
    "nav.profile": "پروفائل",
    "nav.budget": "بجٹ",
    "nav.leader": "لیڈر ٹریکر",
    "nav.infrastructure": "defect",
    "nav.bookmark": "بک مارک",
    "nav.settings": "ترتیبات اور رازداری",
    "nav.language": "زبان (Language)",
    "nav.help": "مدد کا مرکز",
    "nav.home": "ہوم",
    "nav.search": "تلاش کریں",
    "nav.connect": "رابطہ",
    "nav.compose": "شکایت درج کریں",
    "nav.signOut": "سائن آؤٹ",
    "nav.signIn": "سائن ان",
    "nav.theme": "تھیم کی ترجیح",
    "nav.following": "فالو کر رہے ہیں",
    "nav.followers": "فالوورز",
    "nav.guest": "مہمان شہری",
    "nav.signInPrompt": "اپنی شکایات کو ٹریک کرنے کے لیے سائن ان کریں۔",
    "nav.signInBtn": "اکاؤنٹ میں سائن ان کریں",
    "header.title": "اوپن دیش",
    "header.subtitle": "شہری طرز حکمرانی اور جوابدہی",
    "header.searchPlaceholder": "شکایات، رہنما، محکمے تلاش کریں...",
    "header.postGrievance": "شکایت درج کریں",
    "bottom.home": "ہوم",
    "bottom.search": "تلاش",
    "bottom.post": "پوسਟ",
    "bottom.leader": "رہنما",
    "bottom.infra": "انفرا",
    "feed.kyaProblem": "کیا مسئلہ ہے؟",
    "feed.reportIssue": "عوامی شکایت درج کریں",
    "feed.forYou": "آپ کے لیے",
    "feed.following": "فالو کر رہے ہیں",
    "feed.allDepartments": "تمام محکمے",
    "feed.upvote": "حمایت",
    "feed.comment": "تبصرہ",
    "feed.share": "شیئر کریں",
    "feed.sla": "SLA کی آخری تاریخ",
    "feed.underReview": "زیر جائزہ",
    "feed.actionTaken": "کارروائی جاری",
    "feed.resolved": "حل ہو گیا",
    "feed.submitted": "جمع کر دیا گیا",
    "budget.title": "بجٹ لیجر",
    "budget.inflowTab": "آمدنی (Inflow)",
    "budget.outflowTab": "اخراجات (Outflow)",
    "budget.receipts": "کل آمدنی",
    "budget.spending": "کل اخراجات",
    "budget.capex": "سرمایہ کاری (Capex)",
    "lang.selectTitle": "ایپ کی زبان منتخب کریں",
    "lang.selectSubtitle": "اپنی پسندیدہ ہندوستانی زبان منتخب کریں۔",
    "lang.searchPlaceholder": "زبان تلاش کریں...",
    "lang.active": "فعال",
    "lang.apply": "زبان لاگو کریں",
  },
  as: {
    "nav.profile": "প্ৰফাইল",
    "nav.budget": "বাজেট",
    "nav.leader": "নেতা ট্ৰেকাৰ",
    "nav.infrastructure": "আন্তঃগাঁথনি",
    "nav.bookmark": "বুকমাৰ্ক",
    "nav.settings": "ছেটিংছ আৰু গোপনীয়তা",
    "nav.language": "ভাষা (Language)",
    "nav.help": "সহায়তা কেন্দ্ৰ",
    "nav.home": "হোম",
    "nav.search": "সন্ধান কৰক",
    "nav.connect": "সংযোগ",
    "nav.compose": "অভিযোগ দাখিল কৰক",
    "nav.signOut": "ছাইন আউট",
    "nav.signIn": "ছাইন ইন",
    "nav.theme": "থিম পছন্দ",
    "nav.following": "অনুসৰণ কৰি থকা",
    "nav.followers": "অনুসৰণকাৰী",
    "nav.guest": "অতিথি নাগৰিক",
    "nav.signInPrompt": "আপোনাৰ অভিযোগসমূহ ট্ৰেক কৰিবলৈ ছাইন ইন কৰক।",
    "nav.signInBtn": "একাউণ্টত ছাইন ইন কৰক",
    "header.title": "অ'পেন দেশ",
    "header.subtitle": "নাগৰিক প্ৰশাসন আৰু নেতাৰ দায়বদ্ধতা",
    "header.searchPlaceholder": "অভিযোগ, নেতা, বিভাগ সন্ধান কৰক...",
    "header.postGrievance": "অভিযোগ পোষ্ট কৰক",
    "bottom.home": "হোম",
    "bottom.search": "সন্ধান",
    "bottom.post": "পোষ্ট",
    "bottom.leader": "নেতা",
    "bottom.infra": "ইনফ্ৰা",
    "feed.kyaProblem": "কি समस्या হৈছে?",
    "feed.reportIssue": "ৰাজহুৱা অভিযোগ দাখিল কৰক",
    "feed.forYou": "আপোনাৰ বাবে",
    "feed.following": "অনুসৰণ",
    "feed.allDepartments": "সকলো বিভাগ",
    "feed.upvote": "সমৰ্থন",
    "feed.comment": "মন্তব্য",
    "feed.share": "শ্বেয়াৰ",
    "feed.sla": "SLA সময়সীমা",
    "feed.underReview": "পৰ্যালোচনাধীন",
    "feed.actionTaken": "ব্যৱস্থা গ্ৰহণ কৰা হৈছে",
    "feed.resolved": "সমাধান কৰা হৈছে",
    "feed.submitted": "দাখিল কৰা হৈছে",
    "budget.title": "বাজেট লেজাৰ",
    "budget.inflowTab": "ৰাজহ (Inflow)",
    "budget.outflowTab": "ব্যয় (Outflow)",
    "budget.receipts": "মুঠ ৰাজহ",
    "budget.spending": "মুঠ ব্যয়",
    "budget.capex": "মূলধনী ব্যয় (Capex)",
    "lang.selectTitle": "এপৰ ভাষা বাছক",
    "lang.selectSubtitle": "আপোনাৰ পছন্দৰ ভাৰতীয় ভাষা বাছক।",
    "lang.searchPlaceholder": "ভাষা সন্ধান কৰক...",
    "lang.active": "সক্ৰিয়",
    "lang.apply": "ভাষা প্ৰয়োগ কৰক",
  },
};

interface LanguageContextType {
  language: string;
  setLanguage: (langCode: string) => void;
  currentLanguageInfo: LanguageInfo;
  t: (key: string, defaultText?: string) => string;
  isLanguageModalOpen: boolean;
  openLanguageModal: () => void;
  closeLanguageModal: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<string>(() => {
    try {
      return localStorage.getItem("open_desh_language") || localStorage.getItem("opennation_language") || "en";
    } catch {
      return "en";
    }
  });

  const [isLanguageModalOpen, setIsLanguageModalOpen] = useState(false);

  const setLanguage = (langCode: string) => {
    setLanguageState(langCode);
    try {
      localStorage.setItem("open_desh_language", langCode);
    } catch {
      // ignore
    }
  };

  const currentLanguageInfo =
    INDIAN_LANGUAGES.find((l) => l.code === language) || INDIAN_LANGUAGES[0];

  const t = (key: string, defaultText?: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    if (TRANSLATIONS.en && TRANSLATIONS.en[key]) {
      return TRANSLATIONS.en[key];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        currentLanguageInfo,
        t,
        isLanguageModalOpen,
        openLanguageModal: () => setIsLanguageModalOpen(true),
        closeLanguageModal: () => setIsLanguageModalOpen(false),
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
